Parameters:
  FileSystemName:
    Type: String
    Description: The name of the EFS file system.

  Encrypted:
    Type: String
    Description: Specifies whether to enable encryption for the EFS file system.

  PerformanceMode:
    Type: String
    Description: The performance mode for the file system.
    AllowedValues:
      - generalPurpose
      - maxIO

  ProvisionedThroughputInMibps:
    Type: Number
    Description: The throughput limit for the EFS file system in MiB/s when using provisioned throughput mode.

  ThroughputMode:
    Type: String
    Description: The throughput mode for the EFS file system.
    AllowedValues:
      - bursting
      - provisioned

Resources:
  MyEFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: Name
          Value: !Ref FileSystemName
      Encrypted: !Ref Encrypted
      PerformanceMode: !Ref PerformanceMode
      ProvisionedThroughputInMibps: !Ref ProvisionedThroughputInMibps
      ThroughputMode: !Ref ThroughputMode
