AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an S3 bucket with versioning

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket
  AccessControl:
    Type: String
    Description: Access control for the S3 bucket
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
  EnableVersioning:
    Type: String
    Description: Enable versioning for the S3 bucket
    Default: No
    AllowedValues:
      - Yes
      - No

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: !Ref AccessControl
      VersioningConfiguration:
        Status: !If [EnableVersioning, Enabled, Suspended]
